source 'https://rubygems.org'
#gem 'jquery_gantt_rails'
gem 'rabl'
gem 'gon'
gem 'haml'
gem 'haml-rails'
#gem 'erb2haml'
#gem 'rubyzip', '= 0.9.9'
#gem 'websocket', '= 1.0.7'
#gem 'selenium-webdriver', '= 2.35.1'
#gem 'xpath', '= 1.0.0'
#gem 'capybara', '~> 2.0.0'